name: 01 basic first workflow "Learn syntax"
on: workflow_dispatch

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: echo "Hello world from Learn syntax"

