name: 03 basic events filter
on: 
  pull_request:
    types: 
      - closed
  push:
    branches:
      - main

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: echo "hello world from basic events filter"
