name: 04 basic events external filter
on: 
  repository_dispatch:
    types: 
      # was triggerd by github api with create-a-repository-dispatch-event using curl
      - basic-events-external-filter 
 
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: echo "hello world from basic events external filter"
