name: 04 basic events external schedule filter


on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: echo "hello world from basic events external filter"
