name: 06 basic context
run-name: github context run-name by ${{github.actor}} tries "${{github.run_number}}"
on: workflow_dispatch

jobs:
  print-context-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print context Data
        # run: echo ${{github}}
        # run: echo ${{github.actor}}
        # run: echo ${{github.event_name}}
        # run: echo ${{job.status}}
        run: echo ${{toJson(github)}}
  
