name: 08 basic env variables
run-name: define environment variables

on:
  push:
    branches:
      - main
jobs:
  print-env-variable:
    runs-on: ubuntu-latest
    steps:
      - name: print environment variable
        env:
          MY_ENV_VAR: "Hello from environment variable"
        run: echo ${{ env.MY_ENV_VAR }}

  print-config-variable:
    runs-on: ubuntu-latest
    steps:
      - name: print config variable
        run: echo "The config variable is ${{ vars.MY_CONFIG_VAR }}"
